name: macOS build

on:
  push:
    branches:
      - "*"
    pull_request:
      - "*"
    paths:
      # This action only runs on push when C++ files are changed
      - "**.cpp"
      - "**.h"
      - "**.cmake"
      - "**Lists.txt"
      - "**-mac.yml"
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: ${{ matrix.config.name }} (${{ matrix.buildtype }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "macOS 11 - OpenGL", os: macos-11, suffix: "-opengl" }
          - { name: "macOS 12 - OpenGL", os: macos-12, suffix: "-opengl" }
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, suffix: "" }
          - { name: "Ubuntu 20.04", os: ubuntu-20.04, suffix: "" }
        buildtype: [Release, Debug]

    steps:
      - name: Install dependencies
        run: ${{ runner.os == 'macOS' && 'brew install ninja create-dmg' || 'sudo apt-get update && sudo apt-get install cmake ninja-build' }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      # Setup caching of build artifacts to reduce total build time (only Linux and MacOS)
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.config.os }}-${{ matrix.buildtype }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build/${{ matrix.buildtype }} -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DCMAKE_POLICY_DEFAULT_CMP0135=NEW -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build/${{ matrix.buildtype }} --parallel 4 --config ${{ matrix.buildtype }}

      - name: Running tests
        if: runner.os != 'Windows'
        run: |
          ${{github.workspace}}/build/${{ matrix.buildtype }}/tests/galoistest

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.config.os }}${{ matrix.config.suffix }}-${{ matrix.buildtype }}
          path: |
            ${{github.workspace}}/build/${{ matrix.buildtype }}
